---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Evenet Bus Rule stack'

Parameters:
  ConfigurationEBNameParam:
    Type: String
  ConfigurationEBRuleNameParam:
    Type: String
  DescriptionParam:
    Type: String
  EventPatternSource:
    Type: String
  EventPatternDetailType:
    Type: String
  EventPatternState:
    Type: String
  EventRuleTargetArn:
    Type: String
  EventRuleTargetID:
    Type: String

Resources:
  EventBusRules:
    Type: "AWS::Events::Rule"
    Properties:
      Description: !Ref DescriptionParam
      EventBusName: !Ref ConfigurationEBNameParam
      EventPattern:
        source:
          - !Ref EventPatternSource
        detail-type:
          - !Ref EventPatternDetailType
      Name: !Ref ConfigurationEBRuleNameParam
      State: !Ref EventPatternState
      Targets: 
      - 
        Arn: !Ref EventRuleTargetArn
        Id: !Ref EventRuleTargetID